# Training parameters
max_epochs: 50
gradient_clip_val: 10.0

# Optimizer
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.00001
  betas: [0.9, 0.999]

# Learning rate scheduler
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: "min"
  factor: 0.5
  patience: 5
  threshold: 1e-4
  threshold_mode: "rel"
  cooldown: 0
  min_lr: 0.0

# Early stopping
early_stopping:
  enabled: true
  monitor: "val_loss"
  patience: 10
  mode: "min"
  verbose: False

# Checkpointing
checkpoint:
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  save_last: true
  every_n_epochs: 1
  dirpath: "$checkpoints/${model.type}"
  filename: "epoch={epoch}-val_loss={val_loss:.2f}"

# Gradient accumulation (1 = off, >1 = accumulate)
accumulate_grad_batches: 1

# Precision (32-true for full precision, 16-mixed or bf16-mixed for mixed precision)
precision: "32-true"
